name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  test-on-iot-texlive:
    runs-on: ubuntu-24.04
    name: Tests
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run l3build
        run: l3build check --show-log-on-error -q -H
      - name: Archive failed test output
        if: ${{ always() }}
        uses: zauguin/l3build-failure-artifacts@v1
        with:
          name: testfiles
          retention-days: 3

  doc:
    runs-on: ubuntu-24.04
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:latest
    name: Documentation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run l3build
        run: l3build doc -q -H
      - name: Archive documentation
        uses: actions/upload-artifact@v4
        with:
          name: Documentation
          path: "*.pdf"
          retention-days: 5
      - name: move pdf
        run: mkdir -p pdf-output && mv *.pdf pdf-output/.
      - uses: crazy-max/ghaction-github-pages@v4
        # only publish pdf from main branch
        if: github.ref == 'refs/heads/main'
        with:
          target_branch: pdf-output
          build_dir: pdf-output
          commit_message: Publish PDF Output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
